
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Homepage",
  // title: { absolute: "Homepage"},
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <h1>I am default home route</h1>
  );
}
